package net.indrix.maps.dao;

// Generated 16/09/2006 18:01:27 by Hibernate Tools 3.1.0.beta5

/**
 * CityDescription generated by hbm2java
 */
public class CityDescription implements java.io.Serializable {

    // Fields    

    private String name;

    private String description;

    private String coordinates;

    // Constructors

    /** default constructor */
    public CityDescription() {
    }

    /** minimal constructor */
    public CityDescription(String name) {
        this.name = name;
    }

    /** full constructor */
    public CityDescription(String name, String description, String coordinates) {
        this.name = name;
        this.description = description;
        this.coordinates = coordinates;
    }

    // Property accessors
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCoordinates() {
        return this.coordinates;
    }

    public void setCoordinates(String coordinates) {
        this.coordinates = coordinates;
    }

}
