package net.indrix.maps.dao;

// Generated 16/09/2006 18:01:27 by Hibernate Tools 3.1.0.beta5

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

    // Fields    

    private int id;

    private byte stateId;

    private String name;

    // Constructors

    /** default constructor */
    public City() {
    }

    /** full constructor */
    public City(int id, byte stateId, String name) {
        this.id = id;
        this.stateId = stateId;
        this.name = name;
    }

    // Property accessors
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public byte getStateId() {
        return this.stateId;
    }

    public void setStateId(byte stateId) {
        this.stateId = stateId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
